### ISSUE TITLE
Definir Framework de Desenvolvimento

### ISSUE THREAD

**Issue by fabioantony** [fabioantony/2018.2.PIT.ENGSOFT#1]
### Definir Framework de Desenvolvimento

Precisamos definir qual framework iremos utilizar para desenvolver o sistema proposto. Seguem algumas opções:

- [RubyonRails](https://rubyonrails.org/);
- [Django](https://www.djangoproject.com/);
- [React](https://reactjs.org/);
- [Vue](https://vuejs.org/);
- [Node]();
- [Angular]()

**Comment by SilasFonseca** [comment]
Escolho a Django!!
O Django é um framework Web Python de alto nível que incentiva o rápido desenvolvimento e o design limpo e pragmático. Construído por desenvolvedores experientes, ele cuida de grande parte do desenvolvimento da Web, para que você possa se concentrar em escrever seu aplicativo sem precisar reinventar a roda. É grátis e de código aberto.
-[Django](https://www.djangoproject.com/)

Aluno: Silas da Fonseca Barros

**Comment by anthony2703** [comment]
Escolho **Django** também.

**Comment by fabioantony** [comment]
Fechado! é Django na veia!
